### ISSUE TITLE
'Future' object has no attribute 'set_exception_info' exception

### ISSUE THREAD

**Issue by romasku** [ftpsolutions/collapsing-thread-pool-executor#5]
CollapsingThreadPoolExecutor uses old `set_exception_info` method to set exception of Future instance. It isn't available in python3 standard library anymore:
```
  AttributeError: 'Future' object has no attribute 'set_exception_info'
  File "collapsing_thread_pool_executor/collapsing_thread_pool_executor.py", line 118, in run
    work_item.run()
  File "collapsing_thread_pool_executor/collapsing_thread_pool_executor.py", line 57, in run
    self.future.set_exception_info(e, tb)
```
(check https://docs.python.org/3.8/library/concurrent.futures.html#future-objects)

**Comment by initialed85** [comment]
This has been addressed thanks to your PR at https://github.com/ftpsolutions/collapsing-thread-pool-executor/pull/6; new release is out at https://pypi.org/project/collapsing-thread-pool-executor/2020.7.18/
